### PR TITLE
Update setup.sh

### PR DESCRIPTION
**Pull request by lonesta**

### CODE REVIEW

**Comment by jawj** [comment]
You're changing the default from on-demand connections enabled to disabled on Apple platforms. I can see arguments on both sides. Do you have a specific rationale here?

**Comment by lonesta** [comment]
> You're changing the default from on-demand connections enabled to disabled on Apple platforms. I can see arguments on both sides. Do you have a specific rationale here?

On my device with iOS 12.4, OnDemandEnabled doesn't allow turning off vpn ever

**Comment by jawj** [comment]
Ah — maybe I should add a note on the to the README. The solution is to create a second, dummy VPN manually. I use the server 127.0.0.1 and an em dash (—) as the name. It doesn't matter that this won't connect: you just switch to that VPN in the interface, without connecting, and you'll disconnect from the real VPN.

Screenshot

**Comment by jawj** [comment]
Maybe I should add an option in the script that lets you choose whether connect-on-demand should be enabled, though. I'll ponder.

**Comment by lonesta** [comment]
It seems to me that people initially when working with VPN imply transparent disconnection / connection, it seems to me this is a simpler solution, and creating additional VPNs seems to be a hack

**Comment by jawj** [comment]
Maybe. But a lot of the value of a VPN comes from sending all your traffic over it, and if you connect it manually then it's only a matter of time before it (non-transparently) disconnects again. That's why connect-on-demand is so valuable. And you can't get it without having it set in the `.mobileconfig` file. I continue to ponder ...

**Comment by lonesta** [comment]
It might be better to make this option customizable.

**Comment by lonesta** [comment]
I use vpn only when necessary, and not constantly

**Comment by johncsuti** [comment]
> 
> 
> I use vpn only when necessary, and not constantly

This is not entirely true. If you would like to disable the VPN please press the i in a circle next to the name. You will then have an option to turn off "on-demand" connections. This will prevent the VPN from auto connecting whenever it can. I use it all the time for turning it off and on.

**Comment by jawj** [comment]
> > If you would like to disable the VPN please press the i in a circle next to the name. You will then have an option to turn off "on-demand" connections. This will prevent the VPN from auto connecting whenever it can. I use it all the time for turning it off and on. I would request an option to enable or disable the option by default in the config.

Yes, I think that behaviour may have changed in an iOS update since this issue was filed. It is certainly now possible to turn off 'Connect On Demand' by the method you describe, so I'm going to close the issue.

Anyone who really doesn't want Connect On Demand can edit either the setup script or the generated .mobileconfig to change it.

**Pull request closed without merging**
